import {NextResponse} from "next/server";
import {commanderPage,EdhrecError} from "../../../lib/edhrec";
import {localize} from "../../../lib/messages";
export const runtime="nodejs";
const ua={"Content-Type":"application/json","User-Agent":"PreconUpgradeResearch/1.0 (Commander deck helper)"};
const normalize=(s:any)=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const slug=(s:string)=>normalize(s).replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const headersRe=/^(commanders?|comandanti?|creatures?|creature|planeswalkers?|instants?|istantanei|sorceries|stregonerie|enchantments?|incantesimi|artifacts?|artefatti|lands?|terre|other spells|altre magie|sideboard|maybeboard)\s*:?[ ]*$/i;
function parseDeck(text:string){return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).flatMap(line=>{const m=line.match(/^(\d+)\s*[xX]?\s+(.+)$/);const name=(m?m[2]:line).trim();if(!m&&headersRe.test(name))return[];return[{name,quantity:m?Number(m[1]):1}]})}
async function collection(names:string[]){const cards:any[]=[];const missing:any[]=[];for(let i=0;i<names.length;i+=75){const r=await fetch("https://api.scryfall.com/cards/collection",{method:"POST",headers:ua,body:JSON.stringify({identifiers:names.slice(i,i+75).map(name=>({name}))}),cache:"no-store"});if(!r.ok)throw new Error("Scryfall non è disponibile. Riprova tra poco.");const d=await r.json();cards.push(...(d.data||[]));missing.push(...(d.not_found||[]));}return{cards,missing}}
export async function POST(req:Request){const out=(d:any,init?:ResponseInit)=>NextResponse.json(localize(d,req.headers.get("x-lang")==="en"),init);try{const{deck,commander,budget="",count=5}=await req.json();if(!commander?.trim()||!deck?.trim())return out({error:"Inserisci il comandante e la lista del precon."},{status:400});const entries=parseDeck(deck);if(!entries.length)return out({error:"Lista vuota o non riconosciuta."},{status:400});const base=await collection([...new Set(entries.map(x=>x.name)),commander.trim()]);const commanderCard=base.cards.find(c=>normalize(c.name)===normalize(commander))||base.cards.find(c=>c.type_line?.includes("Legendary Creature")&&normalize(c.name).includes(normalize(commander)));if(!commanderCard)return out({error:`Scryfall non riconosce il comandante “${commander}”. Inserisci il nome ufficiale della carta.`},{status:400});const deckCards=base.cards.filter(c=>entries.some(e=>normalize(e.name)===normalize(c.name))).map(c=>({...c,quantity:entries.find(e=>normalize(e.name)===normalize(c.name))?.quantity||1}));if(!deckCards.length)return out({error:"Nessuna carta del mazzo riconosciuta da Scryfall."},{status:400});let payload:any;try{payload=await commanderPage(commanderCard.name);}catch(err){return out({error:err instanceof EdhrecError&&err.status===429?err.message:"Non riesco a leggere i dati EDHREC ora. Puoi comunque aprire i link di confronto qui sotto."},{status:err instanceof EdhrecError&&err.status===429?429:502});}const lists=payload?.container?.json_dict?.cardlists||[];const stats=new Map<string,{name:string;synergy:number;inclusion:number;decks:number}>();for(const list of lists){for(const v of list.cardviews||[]){if(!v.name)continue;const k=normalize(v.name);const prev=stats.get(k);const item={name:v.name,synergy:Number(v.synergy??-999),inclusion:Number(v.inclusion??0),decks:Number(v.num_decks??v.inclusion??0)};if(!prev||item.synergy>prev.synergy)stats.set(k,item);}}if(!stats.size)return out({error:"EDHREC non ha restituito dati leggibili per questo comandante."},{status:502});const deckSet=new Set(deckCards.map(c=>normalize(c.name)));const identity=commanderCard.color_identity||[];const max=Math.min(10,Math.max(1,Math.floor(Number(count)||5)));
const raw=String(budget??"").trim();const limit=raw?Number(raw.replace(/€/g,"").replace(/\s/g,"").replace(",",".")):null;
if(limit!==null&&(!Number.isFinite(limit)||limit<0))return out({error:"Budget non valido."},{status:400});
const cap=limit===null?null:Math.floor(limit*100);
const group=(c:any)=>["Land","Creature","Artifact","Enchantment","Instant","Sorcery","Planeswalker","Battle"].find(t=>String(c?.card_faces?.[0]?.type_line||c?.type_line||"").includes(t))||"Other";
const img=(c:any)=>c?.image_uris?.normal||c?.card_faces?.find((f:any)=>f.image_uris?.normal)?.image_uris?.normal||null;
const possible=[...stats.values()].filter(s=>!deckSet.has(normalize(s.name))).sort((a,b)=>b.synergy-a.synergy||b.inclusion-a.inclusion).slice(0,150);
const verified=await collection(possible.map(x=>x.name));const byName=new Map(verified.cards.map(c=>[normalize(c.name),c]));
const cuts=deckCards.filter(c=>normalize(c.name)!==normalize(commanderCard.name)).map(c=>({...c,synergy:stats.get(normalize(c.name))?.synergy??null}));
const used=new Set<string>();const swaps:any[]=[];let spent=0;
for(const stat of possible){if(swaps.length>=max)break;const card=byName.get(normalize(stat.name));
if(!card||card.legalities?.commander!=="legal"||!(card.color_identity||[]).every((c:string)=>identity.includes(c))||deckSet.has(normalize(card.name)))continue;
const price=card.prices?.eur;const cents=price!==null&&price!==undefined&&Number.isFinite(Number(price))&&Number(price)>=0?Math.round(Number(price)*100):null;
if(cap!==null&&(cents===null||spent+cents>cap))continue;
const cut=cuts.filter(c=>!used.has(normalize(c.name))&&group(c)===group(card)).sort((a,b)=>(a.synergy??Infinity)-(b.synergy??Infinity))[0];
if(!cut||(cut.synergy!==null&&cut.synergy>=stat.synergy))continue;
used.add(normalize(cut.name));spent+=cents??0;
swaps.push({add:card.name,cut:cut.name,addImage:img(card),cutImage:img(cut),priceEUR:cents===null?null:cents/100,addSynergy:stat.synergy,addInclusion:stat.inclusion,cutSynergy:cut.synergy,reason:cut.synergy===null?`Alternativa dello stesso tipo (${group(card)}). La carta tolta non compare nelle statistiche disponibili: non significa che sia peggiore. Verifica il taglio.`:`Alternativa dello stesso tipo (${group(card)}) con punteggio EDHREC maggiore. Verifica ruolo e sinergie.`});}
const commanderImage=img(commanderCard);const totalPriceEUR=spent/100;const priceComplete=swaps.every(s=>s.priceEUR!==null);const selectionNotice=swaps.length<max?`Trovati ${swaps.length} cambi su ${max} richiesti nei limiti di budget e dati disponibili.`:"";
const siteSlug=slug(commanderCard.name);return out({commander:commanderCard.name,deckCount:deckCards.length,total:deckCards.reduce((n,c)=>n+c.quantity,0),missing:base.missing.filter(x=>normalize(x.name)!==normalize(commanderCard.name)).map(x=>x.name),swaps,commanderImage,totalPriceEUR,priceComplete,selectionNotice,edhrecDecks:payload?.container?.json_dict?.header||null,links:[{name:"EDHREC — raccomandazioni comandante",url:`https://edhrec.com/commanders/${siteSlug}`},{name:"EDHREC — guide upgrade precon",url:"https://edhrec.com/precon"},{name:"Guide precon su MTGGoldfish",url:`https://www.google.com/search?q=${encodeURIComponent(`site:mtggoldfish.com/articles ${commanderCard.name} precon upgrade`)}`},{name:"Guide precon su TCGplayer",url:`https://www.google.com/search?q=${encodeURIComponent(`site:tcgplayer.com ${commanderCard.name} precon upgrade`)}`},{name:"Mazzi pubblici su Archidekt",url:`https://archidekt.com/commanders/${siteSlug}`},{name:"Scryfall — controlla le carte",url:`https://scryfall.com/search?q=${encodeURIComponent(`commander:${commanderCard.name}`)}`}],warning:"I tagli sono una stima meccanica basata su statistiche EDHREC: non equivalgono a una valutazione strategica umana. Controlla ogni sostituzione prima di acquistare."});}catch(e){console.error(e);return out({error:e instanceof Error?e.message:"Errore durante il confronto."},{status:500})}}
